# Generated by Django 5.1.2 on 2024-12-06 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_rename_salname_salons_name'),
        ('bookingapp', '0003_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('request', models.CharField(max_length=100)),
                ('serviceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.services')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.register')),
            ],
        ),
    ]
