# Generated by Django 5.1.2 on 2024-12-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0004_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
