# Generated by Django 5.1.2 on 2024-12-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0005_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='request',
        ),
    ]
