# Generated by Django 5.1.2 on 2024-11-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('branch', models.CharField(max_length=40)),
                ('image', models.ImageField(default='null.jpg', upload_to='images')),
            ],
        ),
    ]
