# Generated by Django 5.1.2 on 2024-11-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='salname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='sername',
            new_name='sname',
        ),
    ]
