# Generated by Django 5.1.2 on 2024-11-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_rename_salname_services_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='sname',
        ),
    ]
