# Generated by Django 5.1.2 on 2024-11-28 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salons',
            old_name='name',
            new_name='salname',
        ),
    ]
