# Generated by Django 5.1.2 on 2024-11-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_rename_name_salons_salname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salons',
            old_name='salname',
            new_name='name',
        ),
    ]
